class AddColumnToDSales < ActiveRecord::Migration
  def change
    execute "alter table d_sales alter column sale_money1 set default 0"
    execute "alter table d_sales alter column sale_money2 set default 0"
    execute "alter table d_sales alter column sale_money3 set default 0"
    execute "alter table d_sales alter column sale_purika set default 0"
    execute "alter table d_sales alter column sale_today_out set default 0"
    execute "alter table d_sales alter column sale_change1 set default 0"
    execute "alter table d_sales alter column sale_change2 set default 0"
    execute "alter table d_sales alter column sale_change3 set default 0"
    execute "alter table d_sales alter column sale_ass set default 0"
    execute "alter table d_sales alter column recive_money set default 0"
    execute "alter table d_sales alter column pay_money set default 0"
    execute "alter table d_sales alter column sale_cashbox set default 0"
    execute "alter table d_sales alter column sale_changebox set default 0"
    execute "alter table d_sales alter column sale_am_out set default 0"
    execute "alter table d_sales alter column sale_pm_out set default 0"
    execute "alter table d_sales alter column exist_money set default 0"
    execute "alter table d_sales alter column over_short set default 0"

    execute "update d_sales set sale_money1 = 0 where sale_money1 is null"
    execute "update d_sales set sale_money2 = 0 where sale_money2 is null"
    execute "update d_sales set sale_money3 = 0 where sale_money3 is null"
    execute "update d_sales set sale_purika = 0 where sale_purika is null"
    execute "update d_sales set sale_today_out = 0 where sale_today_out is null"
    execute "update d_sales set sale_change1 = 0 where sale_change1 is null"
    execute "update d_sales set sale_change2 = 0 where sale_change2 is null"
    execute "update d_sales set sale_change3 = 0 where sale_change3 is null"
    execute "update d_sales set sale_ass = 0 where sale_ass is null"
    execute "update d_sales set recive_money = 0 where recive_money is null"
    execute "update d_sales set pay_money = 0 where pay_money is null"
    execute "update d_sales set sale_cashbox = 0 where sale_cashbox is null"
    execute "update d_sales set sale_changebox = 0 where sale_changebox is null"
    execute "update d_sales set sale_am_out = 0 where sale_am_out is null"
    execute "update d_sales set sale_pm_out = 0 where sale_pm_out is null"
    execute "update d_sales set exist_money = 0 where exist_money is null"
    execute "update d_sales set over_short = 0 where over_short is null"
  end
end
